name: Actionlint

on:
    pull_request:
    push:
        branches:
            - main

jobs:
    actionlint:
        name: actionlint
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v6

            - name: Run actionlint
              uses: devops-actions/actionlint@v0.1.10
